### ISSUE TITLE
Data potentially mis-mapped

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#18]
On the corpus map, there is an instance where the composer Anton Webern – data for him might not be correct as his death is listed as Austria, but is located in New Hampshire.

I would suggest looking to see if the source of the data is incorrect first, and then correcting it there if it is. If the source data is correct, then it was likely something in the transformation to GeoJSON. If that's the case please loop in @bel28kent so that he can log this issue so that its clear in the documentation if someone wanted to reproduce with the correct data

**Comment by epoudrier** [comment]
The source metadata seems correct in the master spreadsheet. This might be a conversion error. @jasonleeubc

**Comment by jasonleeubc** [comment]
The coordinates for Webern's death place are already wrong in the csv file. The coordinates in the csv are listed as (44.18, -71.71), which is correctly plotted on the map. Those coordinates do indicate New Hampshire, USA instead of Austria.

The same kind of problem seems to apply also to the death place of Falla. The place is named as Alta Gracia, Argentina, but the coordinates indicate a location in South Carolina, USA. A thorough check of all coordinates might be necessary.

**Comment by epoudrier** [comment]
Could you verify these based on the FDS master? It should not be too onerous as there will only be 40 locations to check.

**Comment by jasonleeubc** [comment]
I can't find the relevant data in the FDS master spreadsheet. What tab are they under?

**Comment by epoudrier** [comment]
Columns X and Y provide the bith place and death place.

If you were referring to the coordinates, these are only in the csv files
we got from Carto.
