### ISSUE TITLE
render-events-in-chronological-order

### ISSUE THREAD

**Issue by lilydemet** [polyrhythm-project/polyrhythm-maps#29]
The timeSlider function is successfully rendering events one by one in response to a user interacting with the graphic time slider. And the labels dynamically displayed correspond to the `first_public_performance` timeAttribute option. However, this property of the corpus.js is a string (the timeAttribute option of the timeSlider function seems only able to take a string input). This means the function is not evaluating a number and therefore is rendering events not chronologically, as desired, but in the linear order the dataset has the events stored in. @craigsapp I'd appreciate if you could play around on this branch and see what can be done.

**Comment by craigsapp** [comment]
Note that `options` on the line (currently line 107 in `timeline/timeline-1.html`):

```javascript
        options.markers[ui.value].feature.properties.first_publication_year)
```

is not defined:

<img width="896" alt="Screenshot 2023-04-20 at 8 15 39 AM" src="https://user-images.githubusercontent.com/3487289/233410739-a7942e43-d29a-40f4-872e-362f8cb275ad.png">

This might be related to the sorting problem.

**Comment by craigsapp** [comment]
Related URLs:

https://stackoverflow.com/questions/36012119/leaflet-slider-and-marker-cluster-time-not-sorted
https://gis.stackexchange.com/questions/444088/filter-markers-by-date-in-leaflet

One of the above links (or another page) seems to say that you have to sort the markers yourself (see code below) since the slider plugin does not have functionality to do it itself.   There is also the complication that the time markers are strings instead of integers (which might be causing automatic sorting).  One related problem is there is one entry "N/A" which I convert to the year 3000 when sorting the markers by `first_publication_date`.

Here is the sorting of the timeline slider markers that I added:

```javascript
      //Sort markers by first_publication_year
      sliderControl.options.markers.sort(function (a, b) {
         let A = a.feature.properties.first_publication_year;
         let B = b.feature.properties.first_publication_year;
         A = parseInt(A);
         if (Number.isNaN(A)) A = 3000;
         B = parseInt(B);
         if (Number.isNaN(B)) B = 3000;
         if (A < B) {
            return -1;
         } else if (B < A) {
            return 1;
         } else {
            return 0;
         }
      });
```

**Comment by craigsapp** [comment]
There is one "N/A" entry in the events for an unknown first performance date.  Probably this type of event should be removed from the slider events as an enhancement (we can talk with Ève about that this afternoon).

Also there are only about 52 events, and not the full set of 400 that are expected, which I seem to remember from the last meeting you are using a sample set that Jason provided.

**Comment by lilydemet** [comment]
@craigsapp good catch; and, I'm thinking a similar if/else function might work to evaluate and sort the dataset because timeSlider function is written to take string inputs which I agree is the source of the issue. I looked at the final dataset @jasonleeubc pushed yesterday and no properties are "N/A". However, the properties "premiere_date" and "first_publication_year" have different values -- do you know which year the timeline should render?

**Comment by craigsapp** [comment]
The timeline should display the premier date (as it is currently doing).

I was talking with Ève last week on an unrelated look at the metadata but about the same data fields.  The `premier_date` is the full date of the first performance including the month and day (when known):

https://docs.google.com/spreadsheets/d/17rjKQ3lXJHEHAcDfOXTDNX5a0A_jVqwokcaqhd3Ddng/edit#gid=2122541599

<img width="1176" alt="Screenshot 2023-04-20 at 10 37 14 AM" src="https://user-images.githubusercontent.com/3487289/233444688-ae177119-bc40-48b5-b963-877b15a3d059.png">

You are actually using column F in the metadata spreadsheet which is only the year of the first performance (premier):

<img width="1176" alt="Screenshot 2023-04-20 at 10 38 53 AM" src="https://user-images.githubusercontent.com/3487289/233445057-c1425914-1142-4e05-8b90-b4bb374f81e0.png">


The first publication year is the year in which the composition was published on paper (as opposed to the performance):

<img width="1176" alt="Screenshot 2023-04-20 at 10 38 15 AM" src="https://user-images.githubusercontent.com/3487289/233444918-4c458fcf-699d-4a2a-913a-cdada36103a7.png">

There are 6 cases in the full data that are labeled "unknown", but there are also 12 blank entries which are related:

```
  12 
   1 1877
   2 1878
   1 1889
   5 1893
   1 1894
   1 1898
   1 1900
   2 1901
   3 1902
   6 1904
  10 1905
   4 1906
   5 1907
   5 1908
   5 1909
   7 1910
   7 1911
   7 1912
  15 1913
   2 1914
   8 1915
   7 1916
   7 1917
   8 1918
  19 1919
  10 1920
   5 1921
   7 1922
  19 1923
  20 1924
  23 1925
  31 1926
  33 1927
  12 1928
  10 1929
  14 1930
   9 1931
  16 1932
  12 1933
  17 1934
   7 1935
   7 1936
  12 1937
  10 1938
   4 1939
  17 1940
   9 1941
  14 1942
  17 1943
  15 1944
  24 1945
  13 1946
  10 1947
   7 1948
  30 1949
  20 1950
  10 1951
   9 1952
   4 1953
   8 1954
   4 1955
   8 1956
  12 1957
  11 1958
   6 1959
   2 1960
   4 1961
   5 1962
  13 1963
   2 1964
   3 1965
   1 1966
   2 1967
   1 1968
   4 1969
   3 1970
   1 1972
   1 1973
   6 unknown
```

The different between `N/A/` and `unknown` is probably due to the data that @jasonleeubc is starting from is the data from the previous mapping implementation.   We can discuss with @jasonleeubc and @epoudrier about any need to have the most up-to-date premier dates which would be on the spreadsheet linked to above.

The first publication dates are also displayed on this page: https://polyrhythm.humdrum.org/scores, such as:

<img width="498" alt="Screenshot 2023-04-20 at 10 43 39 AM" src="https://user-images.githubusercontent.com/3487289/233446166-a66214aa-a3c4-4477-a98e-0abeafa957a1.png">

Where `1904` is the first publication (or perhaps the composition) date (for the printed score) and `1961` is the publication date for the printed score that Suter (and the Polyrhythm Project) uses.

There is alto the recording date for the performance used in the project, which is not the same as the premier date (as that is often not used for a commercial recording):

https://polyrhythm.humdrum.org/recordings

Example entry:

<img width="968" alt="Screenshot 2023-04-20 at 10 46 20 AM" src="https://user-images.githubusercontent.com/3487289/233447053-c8cd66ed-bb26-4520-bd57-bc8e760ebd26.png">


Where `2000` is the recording release date being used by the Polyrhtyhm Project.

**Comment by epoudrier** [comment]
@jasonleeubc 

Does the new data include a column with on the the year of the premiere?
