### ISSUE TITLE
Marker clusters on the composers map

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#46]
Marker clusters might be good to include on composers map too.

**Comment by bel28kent** [comment]
Added marker clusters to composers.html on branch 48.

**Comment by epoudrier** [comment]
Modify the clusters using Spiderfy. The goal is for points in the same location at the city level are amalgamated preserving the different colour coding for birth and death.

**Comment by bel28kent** [comment]
@epoudrier @ect123 @craigsapp:

I have added spiderfy to the marker clusters on the composers map. These changes were pushed on Branch #48. 

Note that the spiderfy removes the lines we had that connected birth and death locations by composer. 
<img width="1393" alt="Screen Shot 2023-06-28 at 10 31 41 AM" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/81043032/bddb76f6-2837-47fc-a871-5bdbb15afe68">

Also note that the spiderfy lines only seem to be drawn between markers within a certain area of the map at a certain zoom level, so the lines are only being drawn for two clusters in New York, one in Paris, and one in Vienna. 

I added spiderfy separately to the birth clusters and the death clusters, so the spiderfy lines are only drawn between green markers or red markers. However, the user has to zoom in to the closest zoom level to see the markers themselves in order to know which markers are being grouped. This means that at farther zoom levels the marker clusters are not communicating anything about the birth or death of composers to the user. 
<img width="1432" alt="Screen Shot 2023-06-28 at 10 43 59 AM" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/81043032/05549e62-5fa3-407f-b87d-22fced6f6290">

Lastly, there is some bug with this spiderfied cluster in Vienna. After looking at the metadata, the red dot in the middle appears to be the death place marker for Alban Berg, the only composer in the corpus who died in Vienna. However, the popup will not appear when I click on the dot, no matter what zoom level I am at. Also, the red marker is rendering at a lighter opacity than the other red markers.
<img width="97" alt="Screen Shot 2023-06-28 at 10 49 16 AM" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/81043032/b1a6ec9c-c115-4a53-89ec-c3082076d36e">

**Comment by bel28kent** [comment]
Remove marker clusters and spiderfy. 

Restrict zoom level on map to prevent user from seeing street level. Zoom level: 11

Distance markers within one city. (@jasonleeubc)

Layers: (1) Only birth and death locations; (2) locations with lines; (3) includes locations of important events during composers' lifetimes.

Ability to see data for composers as selected by user.

**Comment by bel28kent** [comment]
Documentation for Leaflet layer control: https://leafletjs.com/reference.html#control-layers

**Comment by epoudrier** [comment]
Point have been manually edited to avoid conflation. Marker clusters will not be used for this map given the small number of points.
