### ISSUE TITLE
Reworking the composer menu 

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#67]

**Comment by ect123** [comment]
- [ ] make the list container 375px in height, that way it just expands the menu to the full list
- [ ] remove the term composer
- [ ] change terms "clear filter" to "reset"

**Comment by craigsapp** [comment]
Stying adjusted in commit https://github.com/polyrhythm-project/polyrhythm-maps/commit/ef272620133ea23337e482fe7a3e961f7f605af7

Example:

<img width="958" alt="Screenshot 2023-09-13 at 15 39 16" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/3487289/d511c022-ae1e-45ef-a06b-5282320ebb68">

It would probably work to convert the composer list into a leaflet control panel, since it should fit well under the legend.

Link to temporary location online:

https://maps.polyrhythm.humdrum.org/composers/testing_0724

For Messiaen, and interesting location for him is Stalag VIII-A near Görlitz, Germany from 1940-1942 during WW II:

https://goo.gl/maps/pTfG2eWPA8FCvvbU6
https://en.wikipedia.org/wiki/Stalag_VIII-A
https://holocaustmusic.ort.org/places/camps/western-europe/messiaenolivier

In particular he composed Quartet for the End of Time in this prison camp:

https://en.wikipedia.org/wiki/Quatuor_pour_la_fin_du_temps

**Comment by epoudrier** [comment]
The link to temporary location online does not work. @craigsapp

**Comment by craigsapp** [comment]
I moved it to the current active location:

https://maps.polyrhythm.humdrum.org/composers/composers-map

But eventually it should be moved to:

https://maps.polyrhythm.humdrum.org/composers

(so check there in the future if the first above link does not work).

From the webpage: https://maps.polyrhythm.humdrum.org the link to the composer map is currently working (pointing to composers-map subdirectory).

I need to update the maps links on the https://polyrhythm.humdrum.org website (for composers and timeline, which have changed).

**Comment by epoudrier** [comment]
The selected colour for the background works. Could we make the box around "reset" smaller or a little further away from the last composer's name?
